setup(name='hello',
  version='0.1',
  description='A plugin to say hello',
  url='https://github.com/ikarous/PipTestHello',
  author='William Norris',
  author_email='ike.norris@gmail.com',
  license='MIT',
  packages=['hello'],
  zip_safe=False)
